server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
spring:
  cloud:
    gateway:
      routes:
      - id: coreImageModule
        uri: http://localhost:9820
        predicates:
          - Path=/image/**
      - id: accountModule
        uri: http://localhost:9810
        predicates:
          - Path=/register-account
        filters:
          - Auth
      - id: coreModule
        uri: http://localhost:9820
        predicates:
        - Path=/**
        filters:
        - Auth



app:
  service:
    account: http://localhost:9810

